### ISSUE TITLE
semrep.v1.8 execution error

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [lhncbc/SemRep#1]
Hi,
I have just finished installing semrep following all the steps, however once started the two metamap servers I tried launching semrep, but the output is the following:

>(base) [andrea@andrea ~]$ ./.semrep/bin/semrep.v1.8
bash: ./.semrep/bin/semrep.v1.8: /bin/sh^M: bad interpreter: no such file or directory

this, as far as I've understood, is due to the carriage character ^M, thus I removed all the occurences with:
>sed -i 's/\r//' .semrep/bin/semrep.v1.8

and then I got the same error but in `bin/SEMREPrun.v1.8` this time:
>(base) [andrea@andrea ~]$ ./.semrep/bin/semrep.v1.8
LEXICON_YEAR = >2006<
DATA_YEAR = >2006AA<
/home/andrea/.semrep/bin/SEMREPrun.v1.8 /home/andrea/.semrep/bin/semrep.v1.8.BINARY.Linux -DS -L 2006 -Z 2006AA
./.semrep/bin/semrep.v1.8: /home/andrea/.semrep/bin/SEMREPrun.v1.8: /bin/bash^M: bad interpreter: no such file or directory

I edited once again with sed and I get this now:
>(base) [andrea@andrea .semrep]$ ./bin/semrep.v1.8
LEXICON_YEAR = >2006<
DATA_YEAR = >2006AA<
/home/andrea/.semrep/bin/SEMREPrun.v1.8 /home/andrea/.semrep/bin/semrep.v1.8.BINARY.Linux -DS -L 2006 -Z 2006AA
! Prolog engine initialization failed: could not find bootfile /home/andrea/.semrep/bin/sp-4.4.1/sicstus-4.4.1/bin/sprt.sav

However the `sprt.sav` exists and is exactly where it is expected to be:
>(base) [andrea@andrea .semrep]$ ls bin/sp-4.4.1/sicstus-4.4.1/bin/
charmain.o  intrpt.o  jasper.jar  main.o  prologbeans.jar  spaux.o  spds.sav  spre.sav  sprt.sav  sprt.sav.bak

am I doing something wrong?

**Comment by kilicogluh** [comment]
I don't think I've seen this error before, but it suggests there might be something wrong with the installation.
What is the operating system? Did you download SemRep from the NLM website or from github?

--Halil

**Comment by BrunoLiegiBastonLiegi** [comment]
I'm using manjaro on kernel 5.5.7. The link on the website seems to be broken (this one https://semrep.nlm.nih.gov/SemRep.v1.8_Installation.html), thus I got it from github.
Thanks in advance for the help!

**Comment by kilicogluh** [comment]
I was previously able to build SemRep on RedHat 7 and Ubuntu. I am not familiar with manjaro.
Could you try installing from the compressed file here: https://uofi.box.com/s/9j0z2bb1c3jjcvd07u76g8xxb9zvmqeq

**Comment by BrunoLiegiBastonLiegi** [comment]
A box account is requested, which unfortunately I have not and it is not free. Could you please share the file using some other hosting service like dropbox or drive?

**Comment by kilicogluh** [comment]
Can you try this link: https://drive.google.com/file/d/1UhMdZulHufhNXZWJ-SSUHMw5vCzV0ThK ?

**Comment by BrunoLiegiBastonLiegi** [comment]
Thanks! Downloaded and run installation with no errors

![semrep_install](https://user-images.githubusercontent.com/45011234/76340477-f120e680-62fb-11ea-8549-d735edc76ce4.png)

I tried to keep lexicon files cause otherwise install.sh produced a warning for missing DATA/UMLS_HIERARCHY, and indeed the directory was not there anymore. Is it possible that the script moved or deleted it?
Anyway now it seems to work fine
![semrep](https://user-images.githubusercontent.com/45011234/76341508-70fb8080-62fd-11ea-8273-561f965d46b0.png)

Thank you very much for the help! I think that the issue can be closed now if you agree.

**Comment by kilicogluh** [comment]
If DATA/UMLS_HIERARCHY is missing, you may not get full functionality (ISA relationships will not be extracted).
I suggest downloading the missing files from ftp://lhcftp.nlm.nih.gov/Open-Access-Datasets/SKR/SemRep/dist  (*1.8_hier* files).

**Comment by BrunoLiegiBastonLiegi** [comment]
No, it's not missing anymore. Let me explain, the first time I ran `bin/install.sh` it returned a warning about missing hierarchy, although I'm 100% sure the dir was there cause i am the one who copied it there, however after the script's conclusion hierarchy was not there anymore. Then I tried again but chose to keep lexicon files when asked and this time everything has gone as expected. So the hierarchy now is in `DATA` where it is supposed to be.

However I was looking at the `install.log` here [install.log](https://github.com/lhncbc/SemRep/files/4314077/install.log) and there are two errors that were not printed to stdout/stderr:

1) `find: ‘/home/andrea/.metamap/WSD_Server/wstv-dc’: no such file or directory`

2) `ls: cannot access file: '/home/andrea/.semrep/DATA/ABGENE/Linux': no such file or directory`

**Comment by kilicogluh** [comment]
I believe those log errors can safely be ignored.

Just for sanity, ensure that your `bin/SEMREPrun.v1.8` script has the following:

`export SEMREP_DATA_DIR=$BASEDIR/DATA`
`export ABGENE_DATA_DIR=$SEMREP_DATA_DIR/ABGENE/`

And as long as you have the files in `https://github.com/lhncbc/SemRep/tree/master/DATA/ABGENE`  in your `DATA\ABGENE` directory, it should work fine.

**Comment by BrunoLiegiBastonLiegi** [comment]
Yup it's everything there, thank you!
