### ISSUE TITLE
semrep install fail?

### ISSUE THREAD

**Issue by b0ynextd00r** [lhncbc/SemRep#3]
Hi, thank you for this useful tool.

I installed semrep by following https://semrep.nlm.nih.gov/SemRep.v1.8_Installation.html step by step. 

But it seems semrep didn't work:
![image](https://user-images.githubusercontent.com/58327476/103137366-4dc28600-4703-11eb-98d9-f61f4d900f0e.png)

When I use `./bin/semrep.v1.8 InputFile OutputFile` the semrep returned error:
![image](https://user-images.githubusercontent.com/58327476/103137544-a8a8ad00-4704-11eb-9f8b-fa47aeb4b42a.png)

Could you please give me some hint to fix this?
(P.S. The metamap work perfectly)

Thank you very much!

**Comment by b0ynextd00r** [comment]
the install.log also showed file missing:

> cp: cannot stat '/home/abc/semrep_install/public_semrep/DATA/LEXICON/*2018*': No such file or directory
> find: ‘/home/abc/semrep_install/public_mm/WSD_Server/wstv-dc’: No such file or directory
> ls: cannot access '/home/abc/semrep_install/public_semrep/DATA/ABGENE/Linux': No such file or directory

**Comment by kilicogluh** [comment]
Two things to try:

- Ensure that `abgenemod.so` is in your `public_semrep/bin` directory.
- Ensure that in `public_semrep/lib`, there is a symbolic link named `libpcre.so` to the `pcre` shared library in that directory.

Halil

**Comment by b0ynextd00r** [comment]
hi,

Sorry for the late reply.

I checked the files you mentioned, `abgenemod.so` is indeed in` public_semrep/bin` directory and `libpcre.so` is indeed in `public_semrep/lib`, but there is no `pcre` file or foler in `public_semrep/lib`.
![image](https://user-images.githubusercontent.com/58327476/104084529-ca686f00-5282-11eb-8f2a-324ae0349722.png)

**Comment by kilicogluh** [comment]
The likely issue is that the correct `pcre` library cannot be found.
Check what `libpcre.so` file is symbolically linking to.  Is it  `libpcre.so.0.0.1`?  

You might also need to create another symbolic link in `public_semrep/lib` using the command `ln -s libpcre.so.0.0.1 libpcre.so.1`. 
I _think_  in this command `libpcre.so.0.0.1` could also be replaced with another `pcre` library your system already has. 

Halil

**Comment by Downchuck** [comment]
```
ln -s libpcre.so libpcre.so.1
```

they're all linked to 0.0.1, but that .so.1 link isn't included.

```
lrwxr-xr-x    1 1000     50              10 Jan 10 18:34 libpcre.so.1 -> libpcre.so
lrwxr-xr-x    1 1000     50              16 Jun 29  2019 libpcre.so -> libpcre.so.0.0.1
-rwxr--r--    1 1000     50          356340 Jun 18  2019 libpcre.so.0.0.1
```

**Comment by b0ynextd00r** [comment]
I created the symbolic link, but there is still a connection error
![image](https://user-images.githubusercontent.com/58327476/104713871-6dc3f300-575f-11eb-9dc1-c72adb5c538c.png)

**Comment by kilicogluh** [comment]
This is a different error, and I believe it is an input problem. Ensure that the input file ends with a newline character and that the input is in ASCII. 
A Java class is provided for converting to ASCII for convenience: https://metamap.nlm.nih.gov/ReplaceUTF8.shtml

Halil

**Comment by b0ynextd00r** [comment]
Ok, thank you for your help, I'll check my input.

**Comment by yli90** [comment]
> The likely issue is that the correct `pcre` library cannot be found.
> Check what `libpcre.so` file is symbolically linking to. Is it `libpcre.so.0.0.1`?
> 
> You might also need to create another symbolic link in `public_semrep/lib` using the command `ln -s libpcre.so.0.0.1 libpcre.so.1`.
> I _think_ in this command `libpcre.so.0.0.1` could also be replaced with another `pcre` library your system already has.
> 
> Halil
cd to the semrep/lib category and use ln -s libpcre.so.0.0.1 libpcre.so.1, works for me thanks a lot!
