### ISSUE TITLE
Insufficient memory error for sentence

### ISSUE THREAD

**Issue by sanyabt** [lhncbc/SemRep#4]
Hi @kilicogluh, thank you for making this resource available. I am facing a 'Resource error: insufficient memory' error while running SemRep on the Linux command line. The sentence it was trying to process has over 800 characters.

Is there a way to increase the memory available for the program? And does this error occur due to size of the sentence or insufficient RAM? I can also break down the sentence - please let me know what is the maximum number of characters in input. 

Thanks for your help!

**Comment by kilicogluh** [comment]
@sanyabt, can you share the sentence you're trying to process? There is no character limit, but if the sentence is not very well-formed, it may cause problems.

**Comment by sanyabt** [comment]
Closing this for now as I don't have the sentence saved anymore. Thank you for the response!
